[package]
name = "quilt"
version = "0.1.0"
edition = "2021"
authors = ["The quilt team at RC"]

[dependencies]
anyhow = "1.0.51"
clap = { version = "3.0.0-rc.0", features = ["derive"] }
image = "0.23.14"
